config/routes.rb
Rails.application.routes.draw do
  get 'download/index'

  get 'download/pdf'

  root to: "homes#index"
  get "/projects", to: "projects#index", as: "projects"
  get "/about", to: "abouts#index", as: "abouts"
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
  def index
  end

  def pdf
    send_file Rails.root.join('private', 'cv.pdf'), :type=>"application/pdf", :x_sendfile=>true
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/abouts/index.html.erb
<div class="abouts">
  <h1 class="aboutstitle">about_phill.</h1>
  <section class="no-padding" id="portfolio">
    <div class="container-fluid">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <hr class="hrabout primary" style="margin-bottom: 15px;">
        <h3 class="aboutp">  “True wisdom comes to each of us when we realize how little we understand
          about life, ourselves, and the world around us.”
          - Socrates</h3>
          <hr class="primary" style="margin-bottom: 15px;">
        </div>
      </div>
    </section>
</div>

<br>
<br>
<br>

<div class="aboutclass"id="container">
  <div id="leftcol">
    <p><img src="http://s19.postimg.org/ca0qy7c2r/gapicture.jpg" alt="picture of phill">Hi, my name is Phill, I am a problem solver who will bring meaningful web apps to life that inspire passionate followings.
    <p>I was a letter carrier turned programmer, after teaching myself javascript for a couple of months I decided to apply to General Assembly's  12 week Web Development Immersive program. At General Assembly I studied to be a full-stack Web Developer and am now proficient in an array of relevant technologies such as: Javascript, MongoDB, HTML, Ruby on Rails, Angular, CSS, and Git Hub.
  <br>
  </div>
  <div id="rightcol">
    <p>What I love most about building web applications is that it requires diverse types of intelligence and approaches. Most importantly, it requires individuals to come together in order to yield something great. General Assembly provided me with both the projects and the learning environment that promoted independence, the ability to solve problems, and the skill to collaborate with different individuals in web development.
    <p>I am currently living in Walnut Creek with my wife Sherry and our dog Maximilian. I enjoy cooking, photography, hiking, and dog-training.
  </div>
</div>
<br>
<br>
<br>
<div class="container">
  <div class="col-md-12 col-sm-12">

    <section class="no-padding" id="portfolio" style="margin-top: 100px;">
      <div class="container-fluid">
        <div class="col-lg-10 col-lg-offset-1 text-center">
          <hr class="primary" style="margin-bottom: 50px;">

          <button type="button" class="pdfbtn btn btn-default btn-md">
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> <%= link_to ' Click to download my Resume', download_pdf_path %>
          </button>
          <br>
          <br>
          <br>
          <div class="col-lg-12 text-center">
               <i class="fa fa-envelope-o fa-3x sr-contact"></i>
               <p>phillbert.cheng@yahoo.com</p>
          </div>
          <br>
          <br>
          <div align="center" class="socialbtns">
            <ul>
              <li><a href="https://github.com/PJC-1" class="fa fa-lg fa-github"></a></li>
              <li><a href="https://www.linkedin.com/in/phillbertcheng" class="fa fa-lg fa-linkedin"></a></li>
              <li><a href="https://www.instagram.com/maxstaagram/" class="fa fa-lg fa-instagram"></a></li>
            </ul>
          </div>
          <br>
          <br>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/download/pdf.html.erb
<h1>Download#pdf</h1>
<p>Find me in app/views/download/pdf.html.erb</p>

app/views/homes/index.html.erb
    <div class="homepage">
      <h1 class="titles">phill_dev.</h1>
      <br>
        <section class="no-padding" id="portfolio">
          <div class="container-fluid">
            <div class="col-lg-8 col-lg-offset-2 text-center">
              <hr class="hrabout primary" style="margin-bottom: 15px;">
                <p class="homep">
                  full stack web developer
                </p>
              <hr class="primary" style="margin-bottom: 15px;">
            </div>
          </div>
        </section>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Work+Sans:400,300,200,100,500,600,700,800,900', :media => "all" %>
  <meta name="viewport" content="width=device-width" />
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a><%= link_to "phill_dev.", root_path, class: "navbar-brand"%></a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-form pull-right" role="search">
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "About Me", abouts_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <%= yield %>

  <div class="modal-footer">
   <div class="col-md-12 text-center">
     <%= link_to "Home", root_path %>
   </div>
  </div>
</body>
</html>

app/views/projects/index.html.erb
<div class="projects">
  <h1 class="titles">projects.</h1>
  <br>
    <section class="no-padding" id="portfolio">
      <div class="container-fluid">
        <div class="col-lg-8 col-lg-offset-2 text-center">
          <hr class="hrabout primary" style="margin-bottom: 15px;">
            <p class="projectsp">
              "Whatever good things we build end up building us."<br>- Jim Rohn
            </p>
          <hr class="primary" style="margin-bottom: 15px;">
        </div>
      </div>
    </section>
</div>

<div class="container" id="projects">
		<div class="row project" id="ga-extend">
			<h2 class="text-center">Argos</h2>
      <br>
      <br>
			<div class="col-md-6 ">
				<img src="http://s19.postimg.org/4eq7je2g3/news_feed_pic.png">
			</div>
			<div class="col-md-6 project-description">
				<p>Argos is a Social Media Application made for Pet Owners. Argos' user is the dedicated, loving, and compassionate pet owner. Owners' love for their pets is unique and my app delivers a product that enables users to share their special relationship with their critters while helping to organize some of the more tedious aspects of being a pet owner. Users can employ the “Argos Calendar” to set important dates like daily walks or vet visits.</p>
				<p><strong>FEATURES: </strong>Users can create a profile for their pets. With Argos users can add photos to their pet’s profile, and employ a calendar that allows them to set important dates to help organize busy schedules or upcoming events. Lastly, Argos also features a news-feed that keeps the user up to date with followers.</p>
				<p><strong>TECHNOLOGIES: </strong>Ruby on Rails, Bcrypt,  PostgreSQL database, Bootstrap, Cloudinary</p>
        <br>
				<div class="col-xs-6 text-center">
					<a href="https://argosapp.herokuapp.com/">Try Argos!</a>
				</div>
				<div class="col-xs-6 text-center">
					<a href="https://github.com/PJC-1/argos">GitHub</a>
				</div>
			</div>
		</div>
    <br>
    <br>
    <br>
    <div class="row project" id="ga-extend">
      <h2 class="text-center">Pola-Snap</h2>
      <br>
      <br>
      <div class="col-md-6 ">
        <img src="http://s19.postimg.org/e6lhfihur/image.png">
      </div>
      <div class="col-md-6 project-description">
        <p>Pola-Snap is a Photo app that allows users to manage their photos.</p>
        <p><strong>FEATURES: </strong> Users can archive their photographs, “like” other users’ photos, comment on those photos, and enjoy searching for pictures by “tag name”.</p>
        <p><strong>TECHNOLOGIES: </strong>Ruby on Rails, Devise, PostgreSQL database, Cloudinary, Bootstrap</p>
        <br>
        <div class="col-xs-6 text-center">
          <a href="https://polasnap.herokuapp.com/">Try Pola-Snap</a>
        </div>
        <div class="col-xs-6 text-center">
          <a href="https://github.com/PJC-1/photo_app">GitHub</a>
        </div>
      </div>
    </div>
    <br>
    <br>

	</div>